### ISSUE TITLE
HEIMAN HS2IRC (Smart IR Control)

### ISSUE THREAD

**Issue by develop-dvs** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#759]
Hi! Need command:

- Create device
- Learn key
- Send stored key
- Delete device or keycode
- Get list of the stored devices and keys

 
From MQTT Explorer:
```
{"battery":100,"devices":[{"id":1,"key_codes":[1],"model_type":99}],"linkquality":57}
```

Example:
https://www.zigbee2mqtt.io/devices/HS2IRC.html

**Comment by mozolin** [comment]
> Hi! Need command:
> 
Hi, are you interested in the setup examples for this device?

**Comment by develop-dvs** [comment]
Yes, i have this device and I don't know how to interact with it through your plugin. There are no pre-installed interfaces, buttons and other things.

I can send only raw commands in visual interface. Bad, no automation.

**Comment by mozolin** [comment]
Well, I could try to explain what I have found. In Home Assistant, for instance, you can make such a script:
```
heiman_rc_get_list:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: "zigbee2mqtt/0x000d6f0015349546/set"
        payload_template: '{"get_list": ""}'
```
and use this script in your automations. The commands like this one you can make for "Create device", "Learn key", "Send stored key" and "Delete device or keycode".
